@startuml diag_c
title Diagramme de classe

class Batiment {
    - String nom
    + creerZone(): Zone
    + getWeather(): Meteo
}

class Zone {
    - String nom
    - Date dateCapture
    + prendrePhotos()
}

class Meteo {
    - String description
    - String iconUrl
    - double temp
    - double tempRessentie
    - double pression
    - double humidite
    - double vVent
}

class Photo {
    + dessinerPassage()
    + detruirePassage(Passage p)
}

class Passage {
    - int x1
    - int y1
    - int x2
    - int y2
    + relier(Zone autreCote)
}


Batiment "1" --> "*" Zone
Zone "1" --> "4" Photo
Photo "1" --> "*" Passage
Passage "*" --> "1" Zone : autreCote
Zone "1" --> "1" Meteo

@enduml