@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class AreaActivity {
  + editPassages(MenuItem): void
  + update(): void
  + onCreateOptionsMenu(Menu): boolean
  + deleteArea(MenuItem): void
  # onCreate(Bundle): void
  - updateDirection(): void
  # onResume(): void
  + onPrepareOptionsMenu(Menu): boolean
  + editArea(MenuItem): void
}
class AreaRecyclerViewAdapter {
  - mInflater: LayoutInflater
  - mData: List<Area>
  - mClickListener: ItemClickListener
  + setAreas(List<Area>): void
  + onCreateViewHolder(ViewGroup, int): ViewHolder
  ~ getItem(int): Area
  + onBindViewHolder(ViewHolder, int): void
  + getItemCount(): int
  ~ setClickListener(ItemClickListener): void
}
class BuildingActivity {
  - searchContent: String
  - building: Building
  - adapter: AreaRecyclerViewAdapter
  + onCreateOptionsMenu(Menu): boolean
  + updateInterface(): void
  + updateSearchResults(): void
  + update(): void
  + updateData(): void
  + deleteBuilding(MenuItem): void
  # onCreate(Bundle): void
  + createArea(MenuItem): void
  # onResume(): void
  + onItemLongClick(View, int): void
  + onItemClick(View, int): void
  + showBuildingDetails(MenuItem): void
}
class BuildingRecyclerViewAdapter {
  - mInflater: LayoutInflater
  - mData: List<Building>
  - mClickListener: ItemClickListener
  ~ getItem(int): Building
  + setBuildings(List<Building>): void
  + onBindViewHolder(ViewHolder, int): void
  + onCreateViewHolder(ViewGroup, int): ViewHolder
  ~ setClickListener(ItemClickListener): void
  + getItemCount(): int
}
class CameraActivity {
  - executor: Executor
  - imageCapture: ImageCapture
  - file: File
  - previewView: PreviewView
  - direction: Direction
  - cameraProviderFuture: ListenableFuture<ProcessCameraProvider>
  # onCreate(Bundle): void
  - startCamera(): void
  - bindPreview(ProcessCameraProvider): void
}
class EditAreaActivity {
  - east: ImageButton
  - south: ImageButton
  - saved: boolean
  - north: ImageButton
  - takePhotoLauncher: ActivityResultLauncher<Intent>
  - building: Building
  - newArea: boolean
  - oldArea: Area
  - area: Area
  - west: ImageButton
  # onCreate(Bundle): void
  # onDestroy(): void
  + save(MenuItem): void
  + onCreateOptionsMenu(Menu): boolean
  - applyPhotos(): void
}
class EditBuildingActivity {
  - photoChanged: boolean
  - editMode: boolean
  - photo: ImageButton
  - takePhotoLauncher: ActivityResultLauncher<Intent>
  - lastPhotoSelected: File
  - pathPhotoFromCamera: String
  - chooseFromGalleryLauncher: ActivityResultLauncher<Intent>
  - building: Building
  - initPhoto: File
  # onDestroy(): void
  + editOrSaveBuilding(MenuItem): void
  # onCreate(Bundle): void
  - applyPhoto(String): void
  - selectImage(Context): void
  + onCreateOptionsMenu(Menu): boolean
  + onOptionsItemSelected(MenuItem): boolean
  - createImageFile(): File
  - applyMode(boolean): void
  + onPrepareOptionsMenu(Menu): boolean
}
interface ItemClickListener << interface >> {
  + onItemClick(View, int): void
  + onItemLongClick(View, int): void
}
interface ItemClickListener << interface >> {
  + onItemLongClick(View, int): void
  + onItemClick(View, int): void
}
class MainActivity {
  - recyclerView: RecyclerView
  - buildings: List<Building>
  - adapter: BuildingRecyclerViewAdapter
  - searchContent: String
  # onResume(): void
  + onCreateOptionsMenu(Menu): boolean
  # onCreate(Bundle): void
  + saveBuildings(): void
  + updateData(): void
  + onItemClick(View, int): void
  + update(): void
  # onPause(): void
  + updateSearchResults(): void
  + createBuilding(MenuItem): void
  + onItemLongClick(View, int): void
}
class MyActivity {
  # toolbar: MaterialToolbar
  - downX: int
  - showNavigationIcon: boolean
  # setAppBarNavigation(int, int): void
  # initAppBar(String, String, boolean): void
  + dispatchTouchEvent(MotionEvent): boolean
  + onOptionsItemSelected(MenuItem): boolean
  # initAppBar(String, String, boolean, int, int): void
}
interface OnTouchListner << interface >> {
  + afterSelection(SurfaceHolder, Context, double[], SimpleClickEnabler): void
  + onSelection(SurfaceHolder, Context, double[], double[]): void
  + onPassageClick(SurfaceHolder, Context, Passage): void
}
class PassageViewActivity {
  - previousNumberOfPointers: int
  # imageView: ImageView
  - previousSelection: double[]
  - resource: Drawable
  # direction: Direction
  - allowSimpleClick: boolean
  # area: Area
  # building: Building
  # draw(SurfaceHolder, List<Passage>): void
  # draw(SurfaceHolder, List<Passage>, int): void
  # applyImage(File, OnTouchListner): void
  + initSurface(OnTouchListner, Drawable): void
  # draw(SurfaceHolder): void
  - drawPassages(Canvas, List<Passage>, int): void
  # onCreate(Bundle): void
}
class PassagesActivity {
  - editPassage(SurfaceHolder, Passage): void
  # onCreate(Bundle): void
  - selectOtherSide(SurfaceHolder, SelectOtherSide_OnSelectListener, SelectOtherSide_BeforeDismissListener): void
  - savePassages(): void
  - deletePassage(SurfaceHolder, Passage): void
}
interface SelectOtherSide_BeforeDismissListener << interface >> {
  + beforeDismiss(): void
}
interface SelectOtherSide_OnSelectListener << interface >> {
  + onSelect(Area): void
}
interface SimpleClickEnabler << interface >> {
  + enable(): void
}
class ViewHolder {
  ~ descriptionBatiment: TextView
  ~ photoBatiment: ImageView
  ~ nomBatiment: TextView
  + onClick(View): void
  + onLongClick(View): boolean
}
class ViewHolder {
  ~ areaName: TextView
  + onLongClick(View): boolean
  + onClick(View): void
}

AreaActivity                           -[#000082,plain]-^  PassageViewActivity                   
BuildingActivity                       -[#008200,dashed]-^  ItemClickListener                     
BuildingActivity                       -[#000082,plain]-^  MyActivity                            
CameraActivity                         -[#000082,plain]-^  MyActivity                            
EditAreaActivity                       -[#000082,plain]-^  MyActivity                            
EditBuildingActivity                   -[#000082,plain]-^  MyActivity                            
ItemClickListener                      +-[#820000,plain]-  AreaRecyclerViewAdapter               
ItemClickListener                      +-[#820000,plain]-  BuildingRecyclerViewAdapter           
MainActivity                           -[#008200,dashed]-^  ItemClickListener                     
MainActivity                           -[#000082,plain]-^  MyActivity                            
PassageViewActivity                    -[#000082,plain]-^  MyActivity                            
PassagesActivity                       -[#000082,plain]-^  PassageViewActivity                   
ViewHolder                             +-[#820000,plain]-  AreaRecyclerViewAdapter               
ViewHolder                             +-[#820000,plain]-  BuildingRecyclerViewAdapter           
@enduml
